apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: text-classifier-ingress
spec:
  podSelector:
    matchLabels:
      app: text-classifier
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
