apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: text-classifier
spec:
  to:
    kind: Service
    name: text-classifier
  port:
    targetPort: 8000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
