name: iac
on:
  push:
    paths:
      - "terraform/**"
      - ".github/workflows/iac.yml"
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/iac.yml"

permissions:
  contents: read

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloud: [aws, azure, gcp]
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.4"
      - working-directory: terraform/${{ matrix.cloud }}
        run: terraform fmt -check -recursive
      - working-directory: terraform/${{ matrix.cloud }}
        run: terraform init -backend=false
      - working-directory: terraform/${{ matrix.cloud }}
        run: terraform validate
